"use client";

import { useState, type FormEvent } from "react";
import { addLocalDays } from "@/features/tasks/domain/dateWindow";
import type { TaskDraft, TaskPriority } from "@/features/tasks/domain/task";

type TaskComposerProps = { today: string; onClose(): void; onCreate(draft: TaskDraft): Promise<void>; onStartVoice(): void };

export function TaskComposer({ today, onClose, onCreate, onStartVoice }: TaskComposerProps) {
  const [title, setTitle] = useState(""); const [dateChoice, setDateChoice] = useState("today"); const [customDate, setCustomDate] = useState(""); const [time, setTime] = useState(""); const [priority, setPriority] = useState<TaskPriority | "">(""); const [error, setError] = useState<string | null>(null);
  async function submit(event: FormEvent) { event.preventDefault(); if (!title.trim()) return; setError(null); try { await onCreate({ title: title.trim(), scheduledDate: dateChoice === "today" ? today : dateChoice === "tomorrow" ? addLocalDays(today, 1) : customDate || null, scheduledTime: time || null, priority: priority || null, status: "active", inputMethod: "text" }); } catch { setError("Не вдалося зберегти задачу. Спробуйте ще раз."); } }
  return <div className="composer-backdrop" onMouseDown={onClose}><form className="task-composer" role="dialog" aria-modal="true" aria-label="Нова задача" onMouseDown={(event) => event.stopPropagation()} onSubmit={submit}><div className="composer-handle" /><label>Що потрібно зробити?<input autoFocus value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Наприклад, надіслати бриф" /></label><p>Введіть задачу або продиктуйте її</p><div className="composer-controls"><label>Дата<select aria-label="Дата" value={dateChoice} onChange={(event) => setDateChoice(event.target.value)}><option value="today">Сьогодні</option><option value="tomorrow">Завтра</option><option value="custom">Вибрати дату</option></select></label>{dateChoice === "custom" ? <input aria-label="Вибрати дату" type="date" value={customDate} onChange={(event) => setCustomDate(event.target.value)} /> : null}<label>Час<input aria-label="Час" type="time" value={time} onChange={(event) => setTime(event.target.value)} /></label><label>Пріоритет<select aria-label="Пріоритет" value={priority} onChange={(event) => setPriority((event.target.value || "") as TaskPriority | "")}><option value="">Без пріоритету</option><option value="high">Висока</option><option value="medium">Середня</option><option value="low">Мінімальна</option></select></label></div>{error ? <p role="alert" className="capture-error">{error}</p> : null}<div className="composer-actions"><button type="button" aria-label="Записати голосом" className="microphone-button" onClick={onStartVoice}>⌁</button><button type="submit" className="primary-button">Зберегти задачу</button></div></form></div>;
}
