"use client";

import { useState, type FormEvent } from "react";
import { addLocalDays } from "@/features/tasks/domain/dateWindow";
import type { TaskDraft, TaskPriority } from "@/features/tasks/domain/task";

type TaskComposerProps = { today: string; onClose(): void; onCreate(draft: TaskDraft): Promise<void>; onStartVoice(): void };

export function TaskComposer({ today, onClose, onCreate, onStartVoice }: TaskComposerProps) {
  const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [dateChoice, setDateChoice] = useState<"today" | "tomorrow" | "custom" | "none">("today"); const [customDate, setCustomDate] = useState(""); const [time, setTime] = useState("09:00"); const [priority, setPriority] = useState<TaskPriority | "">(""); const [menu, setMenu] = useState<"date" | "time" | "priority" | null>(null); const [error, setError] = useState<string | null>(null);
  const dateLabel = dateChoice === "today" ? "Сьогодні" : dateChoice === "tomorrow" ? "Завтра" : dateChoice === "custom" ? "Дата" : "Без дати";
  async function submit(event: FormEvent) { event.preventDefault(); if (!title.trim()) return; setError(null); try { await onCreate({ title: title.trim(), description: description.trim() || undefined, scheduledDate: dateChoice === "today" ? today : dateChoice === "tomorrow" ? addLocalDays(today, 1) : dateChoice === "custom" ? customDate || null : null, scheduledTime: time || null, priority: priority || null, status: "active", inputMethod: "text" }); } catch { setError("Не вдалося зберегти задачу. Спробуйте ще раз."); } }
  return <div className="composer-backdrop" onMouseDown={onClose}><form className="task-composer" role="dialog" aria-modal="true" aria-label="Нова задача" onMouseDown={(event) => event.stopPropagation()} onSubmit={submit}><div className="composer-handle" /><label>Що потрібно зробити?<input autoFocus value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Наприклад, надіслати бриф" /></label><label>Опис задачі<textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="Додайте деталі" rows={2} /></label><div className="composer-controls"><button type="button" onClick={() => setMenu("date")}>{dateLabel}</button><button type="button" onClick={() => setMenu("time")}>Час</button><button type="button" onClick={() => setMenu("priority")}>Пріоритет</button></div>{menu === "date" ? <div className="composer-popover" role="dialog" aria-label="Вибір дати"><button type="button" onClick={() => { setDateChoice("today"); setMenu(null); }}>Сьогодні</button><button type="button" aria-label="Вибрати завтра" onClick={() => { setDateChoice("tomorrow"); setMenu(null); }}>Завтра</button><label>Вибрати дату<input type="date" value={customDate} onChange={(event) => { setCustomDate(event.target.value); setDateChoice("custom"); }} /></label><button type="button" onClick={() => { setDateChoice("none"); setMenu(null); }}>Без дати</button></div> : null}{menu === "time" ? <div className="composer-popover time-wheel" role="dialog" aria-label="Вибір часу"><label>Години<select value={time.slice(0, 2)} onChange={(event) => setTime(`${event.target.value}:${time.slice(3)}`)}>{Array.from({ length: 24 }, (_, hour) => <option key={hour} value={String(hour).padStart(2, "0")}>{String(hour).padStart(2, "0")}</option>)}</select></label><label>Хвилини<select value={time.slice(3)} onChange={(event) => setTime(`${time.slice(0, 2)}:${event.target.value}`)}>{Array.from({ length: 60 }, (_, minute) => <option key={minute} value={String(minute).padStart(2, "0")}>{String(minute).padStart(2, "0")}</option>)}</select></label><button type="button" onClick={() => setMenu(null)}>Застосувати час</button></div> : null}{menu === "priority" ? <div className="composer-popover" role="dialog" aria-label="Вибір пріоритету">{([['high','Висока'], ['medium','Середня'], ['low','Мінімальна'], ['', 'Без пріоритету']] as const).map(([value, label]) => <button key={label} type="button" onClick={() => { setPriority(value); setMenu(null); }}>{label}</button>)}</div> : null}{error ? <p role="alert" className="capture-error">{error}</p> : null}<div className="composer-actions"><button type="button" aria-label="Записати голосом" className="microphone-button" onClick={onStartVoice}>⌁</button><button type="submit" className="primary-button">Зберегти задачу</button></div></form></div>;
}
